### ISSUE TITLE
Some questions about multi-gpu training

### ISSUE THREAD

**Issue by wanghao14** [TorchSSL/TorchSSL#15]
Firstly, thanks a lot for open source this code base which will help the development of semi-supervised field.  I have questions about multi-gpu training  and look forward to your reply:
As far as I understand, this code supports multi-gpu training and I want to know have you ever tested different parameters in multi-gpu environment,  for example, increasing batch size when using more gpu. And how did you set the parameters in .yaml when you have multiple gpus in one machine?

**Comment by 18445864529** [comment]
The batch size refers to the total batch on all GPUs, so if you are running bsz=64 on 4 GPUs, for example, each GPU has a batch of 64/4=16 on it.

**Comment by wanghao14** [comment]
I know the relation between total batch and the batch assigned to each gpu. Because it is very slow to train the model, I just want to know whether the result will be affected if I can use 8*RTX 3090 and increase the total batch.

**Comment by qianlanwyd** [comment]
Please run all 2^20 iterations and do not change the batch size.
Directly adding more GPUs and increasing the batch will affect the result.

**Comment by manchen1995** [comment]
I have similar question on multi-gpu training. I used the same code and configuration to train on CIFAR10 using Fixmatch with single-gpu and multi-gpu (8 GPU). Training on single-gpu gave me similar results as reported in the table, while training on multi-gpu gave me lower results. Specifically, I got 0.8562 for 40 labels, 0.9468 for 250 labels, 0.9564 for 4000 labels. Thought 250 and 4000 labels performance is close to yours, there is a big gap for 40 labels setting. Could you provide any insights why this happen? Thanks!

**Comment by qianlanwyd** [comment]
> 

Have you tried syncbn in our codes?

**Comment by manchen1995** [comment]
By default it uses syncbn, right?
https://github.com/TorchSSL/TorchSSL/blob/main/fixmatch.py#L158

**Comment by syorami** [comment]
> By default it uses syncbn, right? https://github.com/TorchSSL/TorchSSL/blob/main/fixmatch.py#L158

The CIFAR10 40 labels result is much similar to the original paper. Maybe it's due to the multi-gpu training? The original fixmatch used 4-gpus training.
