### ISSUE TITLE
Varying image sizes

### ISSUE THREAD

**Issue by csterling** [TorchSSL/TorchSSL#18]
Thank you for making you work open source!

I am trying to adapt your code to custom datasets, where images may be non-square and of different sizes. How will this affect the models/SSL methods?

Thanks!

**Comment by houwenxin** [comment]
For custom datasets, we recommend to use the same data loader for ImageNet, what you need to do is to organize your data as: "imagenet"/{train or val }/class name/*.jpg or png..., etc., the data will automatically be read and resized: https://github.com/TorchSSL/TorchSSL/blob/3f6ed0f0d04560ebeb721d78c23bd120eda65790/datasets/ssl_dataset.py#L143
