### ISSUE TITLE
Inquiry on ImageNet dataset

### ISSUE THREAD

**Issue by plxpx** [TorchSSL/TorchSSL#19]
Sorry if the question is silly, but I want to ask whether we need to prepare the ImageNet dataset. I run the code on other datasets and the result turns out perfect. But on ImageNet, it shows like that:
FileNotFoundError: [Errno 2] No such file or directory: './data/imagenet/train'

**Comment by 18445864529** [comment]
Yes, torchvision does not support ImageNet auto-downloading anymore so you have to download it by yourself in advance. I just updated a brief data preparing instruction in the readme, please check it out.

**Comment by plxpx** [comment]
Thank you for your help
