### ISSUE TITLE
Implementation of ReMixMatch

### ISSUE THREAD

**Issue by ZhuoranYu** [TorchSSL/TorchSSL#29]
Hi,

Thanks for your work! I just have a quick question: in the remixmatch paper, they mention that "we generate K strongly-augmented versions of the same unlabeled input" and K is set to 8 for their experiments. 

However, when I check the data loading part of this repo, it seems that only 2 strongly-augmented views are generated(https://github.com/TorchSSL/TorchSSL/blob/2807f4046a873fb3c3d606f2eecdcee010747d43/datasets/dataset.py#L103).

I'm not sure if this is a design choice, a bug, or something I mis-interpret. Can you provide some insights here?

Thanks again!

**Comment by qianlanwyd** [comment]
If we use 8, the batchsize is too big. So we use 2 here.
