### ISSUE TITLE
Trained model weights

### ISSUE THREAD

**Issue by gauravkrnayak** [TorchSSL/TorchSSL#32]
Can you please share the final trained models corresponding to the latest papers mentioned in the readme.

**Comment by qianlanwyd** [comment]
We will consider sharing it.
The size of all logs and weights is about 1000G. We will try to find a way to share it.

**Comment by callmekofi** [comment]
can you share it via Baidu disk? It would be easier to download the final trained models

**Comment by qianlanwyd** [comment]
We have updated the logs and weights we have.
