### ISSUE TITLE
I faced the problem: KeyError: 'eval_model'

### ISSUE THREAD

**Issue by aihcyllop** [TorchSSL/TorchSSL#34]
I have finished running the training of flexmatch and get the saved model.

When I run eval.py, I faced the problem: KeyError: 'eval_model' in line 37.

How can I modify the code in eval.py? Thanks!

**Comment by qianlanwyd** [comment]
Sorry for the inconvenience. Please do not use eval.py at this moment. We are trying to re-organize TorchSSL to make it more kindly and add more algorithms. We will rewrite eval.py then.
If you insist on using it right now, you can modify it by youself
