### ISSUE TITLE
Why do some results of semi-supervised methods could better than supervised methods on CIFAR-10 and SVNH?

### ISSUE THREAD

**Issue by jingzhengli** [TorchSSL/TorchSSL#35]

**Comment by qianlanwyd** [comment]
As you can see in our paper and codes. For supervised learning, we only use weak augmentation. For some SSL methods, we use strong augmentation

**Comment by jingzhengli** [comment]
> As you can see in our paper and codes. For supervised learning, we only use weak augmentation. For some SSL methods, we use strong augmentation

Got it, thanks for the quick reply.
