### ISSUE TITLE
About  running custom dataset

### ISSUE THREAD

**Issue by aihcyllop** [TorchSSL/TorchSSL#37]
Excuse me, I want to run small datasets on flexmatch because cifar-10 is too slow.

I want to ask which part of this code should been modified, or do you have a sample? Thank you.

**Comment by Hhhhhhao** [comment]
For custom dataset, you can modify SSL_Dataset in ssl_dataset.py and create your custom dataset in train.py

Currently we do not have any sample for custom dataset, we'll support it in the future.
