### ISSUE TITLE
about "use_DA" in flexmatch

### ISSUE THREAD

**Issue by anonymoussss** [TorchSSL/TorchSSL#40]
What does the parameter "use_DA" mean?

In main/flexmatch.py line295.
`parser.add_argument('--use_DA', type=str2bool, default=False)`  
In models/flexmatch/flexmatch_utils.py line 33.
```
if use_DA:
            if p_model == None:
                p_model = torch.mean(pseudo_label.detach(), dim=0)
            else:
                p_model = p_model * 0.999 + torch.mean(pseudo_label.detach(), dim=0) * 0.001
            pseudo_label = pseudo_label * p_target / p_model
            pseudo_label = (pseudo_label / pseudo_label.sum(dim=-1, keepdim=True))
```

**Comment by Hhhhhhao** [comment]
The use_DA flag corresponds to using Distribution Alignment, introduced in ReMixMatch. This flag will be removed in the future versions of TorchSSL.

**Comment by anonymoussss** [comment]
Got it, 
thanks for the quick reply :)
