### ISSUE TITLE
Question about the FullySupervised experiment

### ISSUE THREAD

**Issue by syorami** [TorchSSL/TorchSSL#43]
Thanks for your work on collecting those SSL classification methods. I'm a little bit confused about the FullySupervised experiment, which seems to be trained only on a small fraction of labeled samples in configs. While the FullySupervised results remain almost the same in the README, please help clarify the meaning of FullySupervised here.

**Comment by qianlanwyd** [comment]
Sorry for the inconvenience.
As you can see in (https://github.com/TorchSSL/TorchSSL/blob/main/datasets/ssl_dataset.py#L297),
we load all data to labeled dataset when it comes to fully supervised training.

**Comment by syorami** [comment]
Thanks for the clarification.
