### ISSUE TITLE
CIFAR100 400lb accuracy

### ISSUE THREAD

**Issue by Ryoo72** [TorchSSL/TorchSSL#44]
Thank you for your amazing codes :)
btw, I checked the log file you provided, and the best accuracy was in the low 60% at the cifar100 400 label setting. 
How can I get the accuracy of 32.44 +- 1.99 suggested in the paper?

**Comment by qianlanwyd** [comment]
The results in the paper have been updated.
https://arxiv.org/pdf/2110.08263.pdf
