### ISSUE TITLE
supervised to semi-supervised ?

### ISSUE THREAD

**Issue by an99990** [TorchSSL/TorchSSL#46]
Hi,
I just discovered your repo, its great !
However, I was wondering if it was possible to modify for example a supervised training loop that i have to do semi-supervised learning ?
How would one adapt and use your repo to achieve such task ?
for example if i am currently using detectron2 module to do training, is there a way i can modify train.py to do semi-supervised learning ?

Thank you so much !

**Comment by qianlanwyd** [comment]
Sorry, what you are asking is a detection task. We focus on classification task.

**Comment by jindongwang** [comment]
@an99990 Thanks for your interest in this repo! Currently, TorchSSL only supports classification tasks, but we are working on NLP and Speech tasks as well. As for other CV tasks such as detection, do you have any idea to collaborate on more diverse cv tasks? 
@qianlanwyd It is good to hear that other different users want to use our repo for different tasks. We should stay open to provide necessary help.

**Comment by qianlanwyd** [comment]
Ok, I will be willing to help if anyone wants to add detection tasks to TorchSSL.

**Comment by qianlanwyd** [comment]
https://github.com/microsoft/SoftTeacher
Currently this repo supports semi supervised detection

**Comment by qianlanwyd** [comment]
I will close this issue since there is no active discussion.
