### ISSUE TITLE
AttrubuteError 

### ISSUE THREAD

**Issue by tangwwwwww** [TorchSSL/TorchSSL#47]
I put the custom data set using the same data loader as Imagenet, and organize my data as: "imagenet"/{train or val}/class name/*.jpg  
![image](https://user-images.githubusercontent.com/102299380/163201715-abdb2d20-344e-44dd-8c47-0f5a1019012e.png)

But this situation still appears, how should I solve it?  
![image](https://user-images.githubusercontent.com/102299380/163201587-649815a8-8aec-416c-a20c-cdb1655e31b4.png)

and there is the [isic.yaml.] setting.
[isic.txt](https://github.com/TorchSSL/TorchSSL/files/8482243/isic.txt)

**Comment by qianlanwyd** [comment]
First please make sure the label ranges from 0 to N-1, where N is the number of classes

**Comment by tangwwwwww** [comment]
> First please make sure the label ranges from 0 to N-1, where N is the number of classes

Sorry, that might be a silly question.This is a 7 classification task, so I should set num_classes to 6?And I tried,It's still the same problem.

**Comment by qianlanwyd** [comment]
Num_classes should be set to 7.  It’s better to rewrite codes  for your own custom data. Sorry I can’t help you much for your own custom data now. We will upload some tutorials and documents for better understanding.

**Comment by tangwwwwww** [comment]
> Num_classes should be set to 7. It’s better to rewrite codes for your own custom data. Sorry I can’t help you much for your own custom data now. We will upload some tutorials and documents for better understanding in a few months.



> Num_classes should be set to 7. It’s better to rewrite codes for your own custom data. Sorry I can’t help you much for your own custom data now. We will upload some tutorials and documents for better understanding in a few months.

thank you.
