### ISSUE TITLE
What is WideResNetVar?

### ISSUE THREAD

**Issue by kai-wen-yang** [TorchSSL/TorchSSL#54]
Hi~ I see that STL10 uses net: WideResNetVar. What is it? Does it different from WideResNet?

**Comment by qianlanwyd** [comment]
It is wrn37-2.

Kaiwen Yang ***@***.***>于2022年5月10日 周二01:26写道：

**Comment by kai-wen-yang** [comment]
It really confuses me regarding the wrn37. How the 37 is computed and what's the difference between wrn28.

Moreover, in the paper, your citation on wrn37-2 seems to be wrong. [35] does not contain wrn37-2.
<img width="470" alt="批注 2022-05-10 015720" src="https://user-images.githubusercontent.com/92202424/167469358-49481037-0e6a-49f7-a84e-7920c50c9372.png">

**Comment by qianlanwyd** [comment]
“For STL10 experiment, we train a deeper variant of WideResNet-28-2 with four extra residual blocks added before the output layer with the purpose of processing larger images in STL10 (compared with CIFAR images). “

written in [35] Tianyi Zhou, Shengjie Wang, and Jeff Bilmes. Time-consistent self-supervision for semisupervised learning. In ICML, pages [11523–11533](tel:11523%E2%80%9311533). PMLR, 2020.

**Comment by kai-wen-yang** [comment]
> “For STL10 experiment, we train a deeper variant of WideResNet-28-2 with four extra residual blocks added before the output layer with the purpose of processing larger images in STL10 (compared with CIFAR images). “
> 
> written in [35] Tianyi Zhou, Shengjie Wang, and Jeff Bilmes. Time-consistent self-supervision for semisupervised learning. In ICML, pages 11523–11533. PMLR, 2020.

Thanks for the quick reply. I am still confused about how to 37 is computed. [35] seems didn't claim they uses wrn37-2.

**Comment by qianlanwyd** [comment]
Google calls it wrn37-2 in Fixmatch. And the number of parameters of our wrn37-2 is the same with google’s repo. You can probably find an answer in google’s papers.
