### ISSUE TITLE
About loss and Top-1 Acc. curve

### ISSUE THREAD

**Issue by rsek147** [TorchSSL/TorchSSL#6]
Hi, I'm training some FlexMatch models with CIFAR-10 dataset. 

I think the training is going well, but the Loss and Top-1 Acc. curves for 40 labels (orange line on the below Tensorboard screen shot) are in a strange shape. Have you had a similar experience? If you have, could you tell me why this is happening?

![image](https://user-images.githubusercontent.com/23075752/140501929-68d43f8f-1f22-451e-aee0-cbacb3b0da4a.png)

**Comment by 18445864529** [comment]
Though we didn't encounter such phenomena in our experiments, we did notice that when the amount of labeled data is limited (the orange curve in this case), the random sampling of the labeled data is crucial to FlexMatch convergence in the early stage. 
So could you try using some different seeds, e.g. seed=0, and see if this issue still exists? Alternatively, without changing the seed, could you try disabling the threshold warmup (by setting args.thresh_warmup=False) and see if it alleviates the issue?

**Comment by rsek147** [comment]
Thank you! I will try to change the seed.
