### ISSUE TITLE
Fixating the index values for cifar10 dataset in 10 labeled examples

### ISSUE THREAD

**Issue by shreejalt** [TorchSSL/TorchSSL#68]
Hi, 
I was curious that why you fix the index values when we try to train freematch on cifar10 with 10 labeled examples? 
In freematch_entropy.py, at line 183, you try to index the numbers based on the value of the seed. If I comment on that piece of code, I cannot reproduce the numbers. 

Thanks in advance, 
Shreejal

**Comment by Hhhhhhao** [comment]
We fix indices of cifar10 with 10 labels for all algorithms, not only for FreeMatch. This is following FixMatch.

**Comment by qianlanwyd** [comment]
Actually E.2 in https://arxiv.org/pdf/2205.07246.pdf 
The reported results of CIFAR10 (10 labels) in the paper for all algoritms all used fixed index values in our internal repository. When we git push the codes, we forget to modify other algorithm.py, except for FreeMatch and SoftMatch. We will update the related algorithm.py recently.

**Comment by shreejalt** [comment]
Thanks @qianlanwyd  for your response. I got your point. I was just curious that if you are using seed training, then why need to fix the index of labeled examples. 

Also, in SVHN, in the logs of freematch entropy you do warmup training. So, I was confused where the warmup training is used in the latest commit of the freematch

**Comment by qianlanwyd** [comment]
Yes, we used warmup. The codes will be updated recently.

**Comment by qianlanwyd** [comment]
codes updated
