### ISSUE TITLE
how to train custom data?

### ISSUE THREAD

**Issue by hyaihjq** [TorchSSL/TorchSSL#8]
how to train custom data?

**Comment by houwenxin** [comment]
We will support custom data soon. For now, you could check and modify the [get_dset](https://github.com/TorchSSL/TorchSSL/blob/c6ef3159d16e86e8c4e064efd357cae10f1bd7f9/datasets/ssl_dataset.py#L259) and [get_ssl_dset](https://github.com/TorchSSL/TorchSSL/blob/c6ef3159d16e86e8c4e064efd357cae10f1bd7f9/datasets/ssl_dataset.py#L280). Basically, the idea is simple. Just return the custom (images, labels) or (images, labels, unlabeled_images) of your custom data.

**Comment by hyaihjq** [comment]
> We will support custom data soon. For now, you could check and modify the [get_dset](https://github.com/TorchSSL/TorchSSL/blob/c6ef3159d16e86e8c4e064efd357cae10f1bd7f9/datasets/ssl_dataset.py#L259) and [get_ssl_dset](https://github.com/TorchSSL/TorchSSL/blob/c6ef3159d16e86e8c4e064efd357cae10f1bd7f9/datasets/ssl_dataset.py#L280). Basically, the idea is simple. Just return the custom (images, labels) or (images, labels, unlabeled_images) of your custom data for the get_data function.

thank you for your answer!
